src: style(9)

diff --git a/src b/src
--- a/src
+++ b/src
@@ -27,13 +27,13 @@ usage() {
 	exit 1
 }
 
-if [ "$#" = "0" ];then
+if [ "$#" = "0" ]; then
 	usage
 fi
 
 # Check if we have a source tree.
-if [ ! -d "$TOP" ];then
-	echo "[src]: source code directory $TOP doesn't exist." 1>&2
+if [ ! -d "$TOP" ]; then
+	echo "[src]: source code directory $TOP doesn't exist" 1>&2
 	exit 1
 fi
 
@@ -42,10 +42,10 @@ fi
 #   `<executable path and its hard links, if any> . <source paths>'.
 # Example:
 #   `/bin/ed /bin/ed /bin/red . /usr/src/bin/ed'.
-if [ "$1" = "-u" ];then
+if [ "$1" = "-u" ]; then
 	# If in the verbose mode, the actual lines that go to the index
 	# file will be directed to stdout as well.
-	if [ "$2" = "-v" ];then
+	if [ "$2" = "-v" ]; then
 		verbose="1"
 	fi
 	
@@ -53,16 +53,16 @@ if [ "$1" = "-u" ];then
 	rm -f "$INDEX" 2>/dev/null
 	# Create a path for index if it doesn't exist.
 	mkdir -p "$INDEX_DIR" 2>/dev/null
-	if [ $? -ne 0 ];then
-		echo "[src]: can not create directory for index file $INDEX_DIR." 1>&2
+	if [ $? -ne 0 ]; then
+		echo "[src]: can not create directory for index file $INDEX_DIR" 1>&2
 		exit 1
 	fi
 	
 	# Since index file will be situated under /usr/local/share, only
 	# root user will be able to modify the file. We want to check if
 	# we have appropriate permissions for this before we start.
-	if ! touch "$INDEX" 2>/dev/null;then
-		echo "[src]: can not create an index file at $INDEX." 1>&2
+	if ! touch "$INDEX" 2>/dev/null; then
+		echo "[src]: can not create an index file at $INDEX" 1>&2
 		exit 1
 	fi
 	
@@ -85,7 +85,7 @@ if [ "$1" = "-u" ];then
 		# binaries (PROG or PROG_CXX) or scripts (man(1), for example,
 		# is actually a shell script, but we want to be able to search
 		# for its source too).
-		if grep -Eq "(PROG(_CXX)|SCRIPTS)?\??( |	)*=" $mf ;then
+		if grep -Eq "(PROG(_CXX)|SCRIPTS)?\??( |	)*=" $mf ; then
 			# Here we're obtaining paths that this Makefile searches through.
 			# It's stored in `.PATH' variable.
 			sea_paths=$(make -C "$mfd" \
@@ -95,7 +95,7 @@ if [ "$1" = "-u" ];then
 		           	|sed "s/\.//")
 	    	
 	    	# If no such paths, then just skip this Makefile.
-	    	if [ "$sea_paths" = " ." ];then
+	    	if [ "$sea_paths" = " ." ]; then
 	    		continue
 	    	fi
 	    	
@@ -115,7 +115,7 @@ if [ "$1" = "-u" ];then
 	    	                	-or -name "*\.sh" \
 	    	                	-or -name "*\.y" \) \
 	    	                    -maxdepth 1)
-	    		if [ -n "$prog_files" ];then
+	    		if [ -n "$prog_files" ]; then
 					seas="$seas $sea"
 				fi
 	    	done
@@ -136,7 +136,7 @@ if [ "$1" = "-u" ];then
 			   || [ "$bin_and_links" = "/bin/ " ] \
 			   || [ "$bin_and_links" = "/sbin/ " ] \
 			   || [ "$bin_and_links" = "/usr/bin/ " ] \
-			   || [ "$bin_and_links" = "/usr/sbin/ " ];then
+			   || [ "$bin_and_links" = "/usr/sbin/ " ]; then
 				continue
 			fi
 			
@@ -156,8 +156,8 @@ fi
 # second invocation form (searching sources).
 
 # First, check if we have an index file.
-if [ ! -f "$INDEX" ];then
-	echo "[src]: index file $INDEX not found." 1>&2
+if [ ! -f "$INDEX" ]; then
+	echo "[src]: index file $INDEX not found" 1>&2
 	exit 1
 fi
 
@@ -165,11 +165,11 @@ fi
 # (usually more than one path is found, when the program is
 # built of several modules or it also can be that the program
 # includes a source code of some external program).
-if [ "$1" = "-a" ];then
+if [ "$1" = "-a" ]; then
 	all_mode="1"
 	shift
 	
-	if [ "$#" = "0" ];then
+	if [ "$#" = "0" ]; then
 		usage
 	fi
 fi
@@ -179,13 +179,13 @@ tgts="$@"
 for tgt in $tgts;do
 	tgt_path=$(which $tgt 2>/dev/null)
 	
-	if [ "$?" != "0" ];then
-		echo "[src]: $tgt is not found." 1>&2
+	if [ "$?" != "0" ]; then
+		echo "[src]: $tgt is not found" 1>&2
 		continue
 	fi
 	
 	# Resolve symlinks (like tar(1) is a symlink to /usr/bin/bsdtar).
-	# And also escape characters like "[" and "." for executables
+	# And also escape characters like "[" and "" for executables
 	# like [(1) (which is also test(1)) (otherwise, they will be
 	# treated as part of regex sytax by grep(1)).
 	tgt_path=$(realpath "$tgt_path" \
@@ -196,8 +196,8 @@ for tgt in $tgts;do
 	# Looking only into the first part of line, where binaries and links.
 	srcs=$(grep "$tgt_path .*\. " "$INDEX")
 	
-	if [ -z "$srcs" ];then
-		echo "[src]: no sources found for $tgt." 1>&2
+	if [ -z "$srcs" ]; then
+		echo "[src]: no sources found for $tgt" 1>&2
 		continue
 	fi
 	
@@ -206,7 +206,7 @@ for tgt in $tgts;do
 	for src in $srcs;do
 		echo "$src"
 		
-		if [ "$all_mode" != "1" ];then
+		if [ "$all_mode" != "1" ]; then
 			break
 		fi
 	done
